<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateForm4sTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('form4s', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->text("tpname")->nullable();
            $table->bigInteger("t_dob")->nullable();
            $table->text("t_ssn")->nullable();
            $table->text("tpsa")->nullable();
            $table->bigInteger("tcity")->nullable();
            $table->text("county")->nullable();
            $table->text("state")->nullable();
            $table->text("tzc")->nullable();
            $table->text("sname")->nullable();
            $table->bigInteger("s_dob")->nullable();
            $table->text("s_ssn")->nullable();
            $table->text("ssa")->nullable();
            $table->text("s_city")->nullable();
            $table->text("s_county")->nullable();
            $table->text("s_state")->nullable();
            $table->text("s_zc")->nullable();
            $table->bigInteger("s_phone")->nullable();
            $table->text("m_status")->nullable();
            $table->text("s_ex")->nullable();
            $table->text("e_bn")->nullable();
            $table->text("e_bsa")->nullable();
            $table->text("e_city")->nullable();
            $table->text("e_county")->nullable();
            $table->text("e_state")->nullable();
            $table->text("e_zc")->nullable();
            $table->bigInteger("e_phn")->nullable();
            $table->text("e_oc")->nullable();
            $table->text("e_pd")->nullable();
            $table->text("se_bn")->nullable();
            $table->text("se_bsa")->nullable();
            $table->text("se_city")->nullable();
            $table->text("se_county")->nullable();
            $table->text("se_state")->nullable();
            $table->text("se_zc")->nullable();
            $table->bigInteger("se_phn" )->nullable();
            $table->text("se_oc")->nullable();
            $table->text("se_pd")->nullable();
            $table->text("p_nr")->nullable();
            $table->bigInteger("p_phn" )->nullable();
            $table->text("p_sa")->nullable();
            $table->text("p_city")->nullable();
            $table->text("p_county")->nullable();
            $table->text("p_state")->nullable();
            $table->bigInteger("p_zc" )->nullable();
            $table->text("age_1")->nullable();
            $table->text("rel_1")->nullable();
            $table->text("age_2")->nullable();
            $table->text("rel_2")->nullable();
            $table->text("age_3")->nullable();
            $table->text("rel_3")->nullable();
            $table->text("age_4")->nullable();
            $table->text("rel_4")->nullable();
            $table->text("age_5")->nullable();
            $table->text("rel_5")->nullable();
            $table->text("age_6")->nullable();
            $table->text("rel_6")->nullable();
            $table->text("g_lp")->nullable();
            $table->text("g_agi")->nullable();
            $table->text("ins_1")->nullable();
            $table->text("adr_1")->nullable();
            $table->text("toa_1")->nullable();
            $table->bigInteger("ac_1" )->nullable();
            $table->bigInteger("blc_1" )->nullable();
            $table->text("ins_2")->nullable();
            $table->text("adr_2")->nullable();
            $table->text("toa_2")->nullable();
            $table->bigInteger("ac_2" )->nullable();
            $table->bigInteger("blc_2" )->nullable();
            $table->text("ins_3")->nullable();
            $table->text("adr_3")->nullable();
            $table->text("toa_3")->nullable();
            $table->bigInteger("ac_3" )->nullable();
            $table->bigInteger("blc_3" )->nullable();
            $table->text("ins_4")->nullable();
            $table->text("adr_4")->nullable();
            $table->text("toa_4")->nullable();
            $table->bigInteger("ac_4" )->nullable();
            $table->bigInteger("blc_4" )->nullable();
            $table->text("g_total")->nullable();
            $table->text("toc_1")->nullable();
            $table->text("nad_1")->nullable();
            $table->bigInteger("mp_1" )->nullable();
            $table->bigInteger("cl_1" )->nullable();
            $table->bigInteger("ao_1" )->nullable();
            $table->bigInteger("ca_1" )->nullable();
            $table->text("toc_2")->nullable();
            $table->text("nad_2")->nullable();
            $table->bigInteger("mp_2" )->nullable();
            $table->bigInteger("cl_2" )->nullable();
            $table->bigInteger("ao_2" )->nullable();
            $table->bigInteger("ca_2" )->nullable();
            $table->text("toc_3")->nullable();
            $table->text("nad_3")->nullable();
            $table->bigInteger("mp_3" )->nullable();
            $table->bigInteger("cl_3" )->nullable();
            $table->bigInteger("ao_3" )->nullable();
            $table->bigInteger("ca_3" )->nullable();
            $table->text("toc_4")->nullable();
            $table->text("nad_4")->nullable();
            $table->bigInteger("mp_4" )->nullable();
            $table->bigInteger("cl_4" )->nullable();
            $table->bigInteger("ao_4" )->nullable();
            $table->bigInteger("ca_4" )->nullable();
            $table->bigInteger("mp_total" )->nullable();
            $table->bigInteger("cl_total" )->nullable();
            $table->bigInteger("ao_total" )->nullable();
            $table->bigInteger("ca_total" )->nullable();
            $table->text("bx_1")->nullable();
            $table->text("sd_1")->nullable();
            $table->text("c_1")->nullable();
            $table->text("bx_2")->nullable();
            $table->text("sd_2")->nullable();
            $table->text("c_2")->nullable();
            $table->text("bx_3")->nullable();
            $table->text("sd_3")->nullable();
            $table->text("c_3")->nullable();
            $table->text("rp_1")->nullable();
            $table->text("too_1")->nullable();
            $table->text("ai_1")->nullable();
            $table->text("rp_2")->nullable();
            $table->text("too_2")->nullable();
            $table->text("ai_2")->nullable();
            $table->text("rp_3")->nullable();
            $table->text("too_3")->nullable();
            $table->text("ai_3")->nullable();
            $table->text("rp_4")->nullable();
            $table->text("aoo_4")->nullable();
            $table->text("ai_4")->nullable();
            $table->text("lic_1")->nullable();
            $table->bigInteger("pl_1" )->nullable();
            $table->text("it_1")->nullable();
            $table->bigInteger("fv_1" )->nullable();
            $table->bigInteger("lv_1" )->nullable();
            $table->text("lic_2")->nullable();
            $table->bigInteger("pl_2")->nullable();
            $table->text("it_2")->nullable();
            $table->bigInteger("fv_2" )->nullable();
            $table->bigInteger("lv_2" )->nullable();
            $table->text("lic_3")->nullable();
            $table->bigInteger("pl_3" )->nullable();
            $table->text("it_3")->nullable();
            $table->bigInteger("fv_3" )->nullable();
            $table->bigInteger("lv_3" )->nullable();
            $table->text("lic_4")->nullable();
            $table->bigInteger("pl_4" )->nullable();
            $table->text("it_4")->nullable();
            $table->bigInteger("fv_4" )->nullable();
            $table->bigInteger("lv_4" )->nullable();
            $table->text("gfi")->nullable();
            $table->text("d_1")->nullable();
            $table->bigInteger("cmv_1" )->nullable();
            $table->text("d_2")->nullable();
            $table->bigInteger("cmv_2" )->nullable();
            $table->text("d_3")->nullable();
            $table->bigInteger("cmv_3" )->nullable();
            $table->bigInteger("lbd_3" )->nullable();
            $table->bigInteger("amp_3" )->nullable();
            $table->text("d_4")->nullable();
            $table->bigInteger("cmv_4" )->nullable();
            $table->bigInteger("lbd_4" )->nullable();
            $table->bigInteger("amp_4" )->nullable();
            $table->text("d1_5")->nullable();
            $table->bigInteger("cmv1_5" )->nullable();
            $table->bigInteger("lbd1_5" )->nullable();
            $table->bigInteger("amp1_5" )->nullable();
            $table->text("d2_6")->nullable();
            $table->bigInteger("cmv2_6" )->nullable();
            $table->bigInteger("lbd2_6" )->nullable();
            $table->bigInteger("amp2_6" )->nullable();
            $table->text("d1_6")->nullable();
            $table->bigInteger("cmv1_6" )->nullable();
            $table->bigInteger("lbd1_6" )->nullable();
            $table->bigInteger("amp1_6" )->nullable();
            $table->text("d21_6")->nullable();
            $table->bigInteger("cmv21_6" )->nullable();
            $table->bigInteger("lbd21_6" )->nullable();
            $table->bigInteger("amp21_6" )->nullable();
            $table->text("d1_7")->nullable();
            $table->bigInteger("cmv1_7" )->nullable();
            $table->bigInteger("lbd1_7" )->nullable();
            $table->bigInteger("amp1_7" )->nullable();
            $table->text("d2_7")->nullable();
            $table->bigInteger("cmv2_7" )->nullable();
            $table->bigInteger("lbd2_7" )->nullable();
            $table->bigInteger("amp2_7" )->nullable();
            $table->text("d_8")->nullable();
            $table->bigInteger("cmv_8" )->nullable();
            $table->bigInteger("lbd_8" )->nullable();
            $table->bigInteger("amp_8" )->nullable();
            $table->text("d1_9")->nullable();
            $table->bigInteger("cmv1_9" )->nullable();
            $table->bigInteger("lbd1_9" )->nullable();
            $table->bigInteger("amp1_9" )->nullable();
            $table->text("d2_9")->nullable();
            $table->bigInteger("cmv2_9" )->nullable();
            $table->bigInteger("lbd2_9" )->nullable();
            $table->bigInteger("amp2_9" )->nullable();
            $table->text("d3_9")->nullable();
            $table->bigInteger("cmv3_9" )->nullable();
            $table->bigInteger("lbd3_9" )->nullable();
            $table->bigInteger("amp3_9" )->nullable();
            $table->text("d_10")->nullable();
            $table->bigInteger("cmv_10" )->nullable();
            $table->bigInteger("lbd_10" )->nullable();
            $table->bigInteger("amp_10" )->nullable();
            $table->text("d_11")->nullable();
            $table->bigInteger("cmv_11" )->nullable();
            $table->bigInteger("ldb_11" )->nullable();
            $table->bigInteger("amp_11" )->nullable();
            $table->text("d_12")->nullable();
            $table->bigInteger("cmv_12" )->nullable();
            $table->bigInteger("ldb_12" )->nullable();
            $table->bigInteger("amp_12" )->nullable();
            $table->bigInteger("g_1" )->nullable();
            $table->bigInteger("n_1" )->nullable();
            $table->bigInteger("g_2" )->nullable();
            $table->bigInteger("n_2" )->nullable();
            $table->bigInteger("g_3" )->nullable();
            $table->bigInteger("n_3" )->nullable();
            $table->bigInteger("g_4" )->nullable();
            $table->bigInteger("n_4" )->nullable();
            $table->bigInteger("g_5" )->nullable();
            $table->bigInteger("n_5" )->nullable();
            $table->bigInteger("g_6" )->nullable();
            $table->bigInteger("n_6" )->nullable();
            $table->bigInteger("g_7" )->nullable();
            $table->bigInteger("n_7" )->nullable();
            $table->bigInteger("g_8" )->nullable();
            $table->bigInteger("n_8" )->nullable();
            $table->bigInteger("n_9" )->nullable();
            $table->bigInteger("n_10" )->nullable();
            $table->bigInteger("n_11" )->nullable();
            $table->bigInteger("n_12" )->nullable();
            $table->bigInteger("n_13" )->nullable();
            $table->bigInteger("n_14" )->nullable();
            $table->bigInteger("n_15" )->nullable();
            $table->bigInteger("n_16" )->nullable();
            $table->bigInteger("n_17" )->nullable();
            $table->bigInteger("n_18" )->nullable();
            $table->bigInteger("n_19" )->nullable();
            $table->text("prnt")->nullable();
            $table->text("sgn")->nullable();
            $table->text("dt")->nullable();
            $table->text("saapn")->nullable();
            $table->text("saas")->nullable();
            $table->text("dte")->nullable();
            $table->text("ei_box")->nullable();
            $table->text("ei_box2")->nullable();
            $table->text("official_use")->nullable();

            $table->timestamp('created_at')->useCurrent();
            $table->timestamp('updated_at')->useCurrent()->useCurrentOnUpdate();
         });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('form4s');
    }
}
